<wsdl:definitions
     name="File_Write_StuResult"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/SOAApplication/PracticeAdapters/File_Write_StuResult"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/SOAApplication/PracticeAdapters/File_Write_StuResult"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:imp1="http://parctice.com/File_Write_StuResult"
    >
  <plt:partnerLinkType name="Write_plt" >
    <plt:role name="Write_role" >
      <plt:portType name="tns:Write_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/file/SOAApplication/PracticeAdapters/File_Write_StuResult"
              xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://parctice.com/File_Write_StuResult" schemaLocation="../Schemas/file_write_schema.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Write_msg">
        <wsdl:part name="body" element="imp1:stucollection"/>
    </wsdl:message>
    <wsdl:portType name="Write_ptt">
        <wsdl:operation name="Write">
            <wsdl:input message="tns:Write_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
