<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="OPS_BPEL"
     targetNamespace="http://xmlns.oracle.com/SOAApplication/OrderProcessingSystem/OPS_BPEL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/SOAApplication/OrderProcessingSystem/OPS_BPEL"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://schemas.oracle.com/bpel/extension"
    >
    <plnk:partnerLinkType name="OPS_BPEL">
        <plnk:role name="OPS_BPELProvider" portType="client:OPS_BPEL"/>
        <plnk:role name="OPS_BPELRequester" portType="client:OPS_BPELCallback"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://schemas.oracle.com/bpel/extension" location="RuntimeFault.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/SOAApplication/OrderProcessingSystem/OPS_BPEL"
                 schemaLocation="../Schemas/OPS_BPEL.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="OPS_BPELRequestMessage">
        <wsdl:part name="payload" element="client:orderRequest"/>
    </wsdl:message>
    <wsdl:message name="OPS_BPELResponseMessage">
        <wsdl:part name="payload" element="client:orderResponse"/>
    </wsdl:message>
    <wsdl:portType name="OPS_BPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:OPS_BPELRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:portType name="OPS_BPELCallback">
        <wsdl:operation name="processResponse">
            <wsdl:input message="client:OPS_BPELResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
